#!/bin/sh
#
# glue2-ipf - IPF glue2 daemon startup
#
# chkconfig: 2345 40 60
# description: Start IPF glue2 daemon
#
### BEGIN INIT INFO
# Provides: glue2-ipf
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Description:    Start IPF glue2 daemon 
### END INIT INFO
#
# Author: Eric Blau <blau@mcs.anl.gov>
# Author: JP Navarro <navarro@mcs.anl.gov>

# Include lsb functions
source /lib/lsb/init-functions

[ -f /etc/sysconfig/glue2-ipf ] && . /etc/sysconfig/glue2-ipf
[ -f /etc/default/glue2-ipf ] && . /etc/default/glue2-ipf

test "$(logname)" = "${IPF_USER}" && SUDO="" || SUDO="sudo -u ${IPF_USER} -H"

case "$1" in
    start)
	echo -n "Starting Glue2 IPF daemon: "
	[ -z ${IPF_DIR} ] && log_failure_msg "IPF_DIR not set"
        ${SUDO} ${IPF_DIR}/etc/init.d/glue2-ipf.sudo start
	RETVAL=$?
	[ ${RETVAL} -eq 0 ] && log_success_msg || log_failure_msg
	;;
    stop)
	echo -n "Shutting down Glue2 IPF daemon: "
	[ -z ${IPF_DIR} ] && log_failure_msg "IPF_DIR not set"
        ${SUDO} ${IPF_DIR}/etc/init.d/glue2-ipf.sudo stop
	RETVAL=$?
	[ ${RETVAL} -eq 0 ] && log_success_msg || log_failure_msg
	;;
    restart)
	## Stop the service and regardless of whether it was
	## running or not, start it again.
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
	;;
esac
exit 0
