#!/bin/sh -x

PKG=$1
VER=$(cat VERSION$PKG)
REL=$(cat RELEASE)

if [ ! -e VERSION$PKG ]; then
  echo "You may not be in the right place to run upload"
  echo "Please run from the root of the package"
  exit 1
fi


REPO=software.xsede.org
#REPO=localhost

REPO_SOFTWARE=/local/software.xsede.org/development/$PKG
REPO_SUBDIR=$PKG-$VER-$REL

OUTDIR=tmp/$PKG-$VER/
if [ ! -d $OUTDIR ]; then
  echo "Package directory '$OUTDIR' missing"
  exit 1
fi

ssh -l xsedesig  $REPO "mkdir -p $REPO_SOFTWARE/$REPO_SUBDIR"

scp -p tmp/$PKG-$VER-$REL.tgz xsedesig@$REPO:$REPO_SOFTWARE/$REPO_SUBDIR/
scp -p $OUTDIR/docs/* xsedesig@$REPO:$REPO_SOFTWARE/$REPO_SUBDIR/
scp -p $OUTDIR/INSTALL.md xsedesig@$REPO:$REPO_SOFTWARE/$REPO_SUBDIR/
scp -p $OUTDIR/INSTALL.html xsedesig@$REPO:$REPO_SOFTWARE/$REPO_SUBDIR/

ssh -l xsedesig  $REPO "cd $REPO_SOFTWARE; rm latest; ln -s $REPO_SUBDIR latest"
ssh -l xsedesig  $REPO "cd $REPO_SOFTWARE; ln -fs latest/INSTALL* ./"
#ssh -l xsedesig  $REPO "cd $REPO_SOFTWARE; gpg --no-tty --passphrase-file /home/xsedesig/pass --armor --detach-sign $REPO_SOFTWARE/$REPO_SUBDIR/$PKG-$VER-$REL.tgz"
